name: Cinema City Monitor

on:
  schedule:
    - cron: '*/15 * * * *' # Uruchamiaj co 15 minut
  workflow_dispatch: # Pozwala uruchomić ręcznie w dowolnym momencie

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout kod
      uses: actions/checkout@v3

    - name: Ustawienie Pythona
      uses: actions/setup-python@v4
      with:
        python-python: '3.10'

    - name: Instalacja bibliotek
      run: pip install requests

    - name: Uruchomienie skryptu
      env:
        SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
        SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
        RECEIVER_EMAIL: ${{ secrets.RECEIVER_EMAIL }}
      run: python script.py
